#!/bin/bash -ex

function ignore_errors()
{
	set +e
	$("$@")
	set -e
}


if test ! $(which xcodebuild); then
	echo 'Installing XCode...'
	sudo xcode-select --install
fi

if test ! $(which brew); then
	echo 'Installing homebrew...'
	/bin/bash -c '$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)'
fi

brew update

binaries=(
	bash-completion
	cask
	curl
	docker
	docker-machine
	exa
	git
	gpg
	go
	htop
	ncdu
	node
	rbenv
	ruby-build
	screenfetch
	tree
	wget
	yarn
)

# Installing binaries...
brew install ${binaries[@]}

function configure_docker()
{
	echo 'If you run into errors installing Docker, then reboot and try again.'
	brew update
	ignore_errors brew uninstall docker docker-machine docker-compose
	brew install docker docker-machine
	#brew cask install virtualbox
	echo 'Install VirtuaBox from DMG download: https://www.virtualbox.org/wiki/Downloads'
	echo 'After you have installed VirtuaBox, press Enter'; read line
	brew install docker-compose
	ignore_errors docker-machine rm default -y
	docker-machine create default --driver virtualbox
	ignore_errors docker-machine create --driver virtualbox default
	docker-machine env default
	eval $(docker-machine env default)
	ignore_errors docker-machine stop default
	docker-machine start default
	docker-machine env default
	msg="
	To verify your docker install run the following commands:

	eval \"$(docker-machine env default)\"
	docker run hello-world
	"
}

function configure_rbenv()
{
	export PATH="$HOME/.rbenv/bin:$PATH"
	eval "$(rbenv init -)"
	rbenv install 1.9.3-p551 && \
		rbenv global 1.9.3-p551 && \
		rbenv local 1.9.3-p551
}

[ -z $SKIP_DOCKER ] || configure_docker
[ -z $SKIP_RBENV ] || configure_rbenv

brew cleanup
