#!/bin/bash -e

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

apps=(
    appcleaner
    dash
    firefox
    github
    google-chrome
    iterm2
    jdownloader
    jetbrains-toolbox
    slack
    sourcetree
    virtualbox
    vlc
    vscodium
)

# Not installed but maybe later
#   caffeine
#   charles
#   cheatsheet
#   copyq
#   dropbox
#   evernote
#   google-drive
#   google-hangouts
#   heroku-toolbelt
#   java
#   little-snitch
#   macvim
#   shimo
#   skype
#   sublime-text
#   transmit
#   vagrant
#   visual-studio-code

# Install apps to /Applications, rather than default location of /Users/$user/Applications
echo 'Installing Cask Apps...'
brew cask install $HOMEBREW_CASK_OPTS ${apps[@]}

apps=(
    betterzip
    qlcolorcode
    qlmarkdown
    qlprettypatch
    qlstephen
    quicklook-csv
    quicklook-json
    suspicious-package
    webpquicklook
)

echo 'Installing Quick Look Plugins...'
echo 'Notes: In Finder, mark a file and press Space to start Quick Look.'
brew cask install $HOMEBREW_CASK_OPTS ${apps[@]}

apps=(
    homebrew/cask-fonts
    homebrew/cask-versions
    colindean/fonts-nonfree
)
echo 'Installing taps...'
brew tap ${apps[@]}

brew cleanup

echo "$0 $@ done."
