#!/bin/bash -e

if test ! $(which xcodebuild); then
	echo 'Installing XCode...'
	sudo xcode-select --install
fi

if test ! $(which brew); then
	echo 'Installing homebrew...'
	/bin/bash -c '$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)'
fi

# Update homebrew recipes
brew update

binaries=(
	bash-completion
	cask
	curl
	docker
	docker-machine
	exa
	git
	gpg
	go
	htop
	ncdu
	node
	screenfetch
	tree
	wget
	yarn
)

echo 'Installing binaries...'
brew install ${binaries[@]}
brew cleanup

function configure_docker()
{
	brew update
	set +e
	brew uninstall docker docker-machine docker-compose
	set -e
	rm -rf $(brew --cache)
	brew install docker docker-machine
	#brew cask install virtualbox
	echo 'Install VirtuaBox from DMG download: https://www.virtualbox.org/wiki/Downloads'
	echo 'After you have installed VirtuaBox, press Enter'; read line
	brew install docker-compose
	docker-machine create --driver virtualbox default
	docker-machine env default
	eval "$(docker-machine env default)"
	docker-machine start default
	echo '+ docker-machine env default'
	docker-machine env default
	msg="
	To verify your docker install run the following commands:

	eval "$(docker-machine env default)"
	docker run hello-world
	"
}
configure_docker