#!/bin/bash -e

function ignore_errors()
{
	set +e
	$("$@")
	set -e
}

./install-xcode-brew
./install-casks
./install-non-brew-apps

echo 'Put the following export statements in your bash environment file. Default file is ~/bashrc.'
echo ''
cat ./env
echo ''

echo 'Setup your id_rsa keys in ~/.ssh'
