#!/bin/bash -e

echo 'First, setup your id_rsa keys in ~/.ssh'
echo 'Press Enter to continue or CTRL+C to abort';read line

./install-xcode-brew
./install-casks
./install-non-brew-apps

echo 'Put the following export statements in your bash environment file. Default file is ~/bashrc.'
echo ''
cat ./env
echo ''
