#!/bin/bash -e

function install_textmate()
{
    brew install ragel boost multimarkdown hg ninja capnp google-sparsehash libressl
    git clone --recursive https://github.com/textmate/textmate.git
    cd textmate
    ./configure && ninja
}

function install_firefox()
{
	msg="
	Download and install Firefox Developer Edition from https://www.mozilla.org/en-US/firefox/developer/
	"
	echo "$msg"
}

#install_textmate
install_firefox