#!/bin/bash -e

# Everyone has different preferences of apps.
# This is a list of stuff I usually install

apps=(
    alfred
    appcleaner
    dash
    docker
    firefox
    github
    iterm2
    jdownloader
    jetbrains-toolbox
    sourcetree
    virtualbox
    vlc
    vscodium
)

# Already installed:
    google-chrome
    slack

# Not installed but maybe later
    caffeine
    charles
    cheatsheet
    copyq
    dropbox
    evernote
    google-drive
    google-hangouts
    heroku-toolbelt
    java
    little-snitch
    macvim
    shimo
    skype
    sublime-text
    transmit
    vagrant
    visual-studio-code

# Install apps to /Applications, rather than default location of /Users/$user/Applications
echo 'Installing Cask Apps...'
brew cask install --appdir='/Applications' ${apps[@]}

apps=(
    betterzip
    qlcolorcode
    qlmarkdown
    qlprettypatch
    qlstephen
    quicklook-csv
    quicklook-json
    suspicious-package
    webpquicklook
)

echo 'Installing Quick Look Plugins...'
echo 'Notes: In Finder, mark a file and press Space to start Quick Look.'
brew cask install --appdir='/Applications' ${apps[@]}

brew cleanup

# link Alfred
brew cask alfred link

echo "$0 $@ done."
