#!/bin/bash -ex

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

apps=(
    appcleaner
    dash
    github
    iterm2
    jdownloader
    jetbrains-toolbox
    slack
    sourcetree
    vlc
    vscodium
)

# Already installed
#    google-chrome

# Not installed but maybe later
#   caffeine
#   charles
#   cheatsheet
#   copyq
#   dropbox
#   evernote
#   google-drive
#   google-hangouts
#   heroku-toolbelt
#   java
#   little-snitch
#   macvim
#   shimo
#   skype
#   sublime-text
#   transmit
#   vagrant
#   visual-studio-code

# Install apps to /Applications, rather than default location of /Users/$user/Applications
# Installing Cask Apps...
brew cask install $HOMEBREW_CASK_OPTS ${apps[@]}

apps=(
    betterzip
    qlcolorcode
    qlmarkdown
    qlprettypatch
    qlstephen
    quicklook-csv
    quicklook-json
    suspicious-package
    webpquicklook
)

# Installing Quick Look Plugins...
# Notes: In Finder, mark a file and press Space to start Quick Look.
brew cask install $HOMEBREW_CASK_OPTS ${apps[@]}

apps=(
    homebrew/cask-fonts
    homebrew/cask-versions
    colindean/fonts-nonfree
)

# Installing taps...
brew tap ${apps[@]}

brew cleanup

echo "$0 $@ done."
