#!/bin/bash -e

USER_PROFILE_NAME=$1
shift 1

if [ -z $USER_PROFILE_NAME ]; then
	USER_DATA_DIR=$(temp-dir)
	echo "Created USER_DATA_DIR: $USER_DATA_DIR"
else
	USER_DATA_DIR="${HOME}/.chrome_profiles/$USER_PROFILE_NAME"
fi
if [ ! -e $USER_DATA_DIR ]; then
	mkdir -p ${USER_DATA_DIR}
fi

EXE_PATH="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

set -x
"$EXE_PATH" "$@" --user-data-dir="$USER_DATA_DIR" 2>&1 &
{ set +x; } 2>/dev/null


exit 0

# -------------------------------------------------------
#                       Notes
# -------------------------------------------------------

For details open enter this in the Chrome address bar: chrome://version/

